import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["CODEX_PROXY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["CODEX_PROXY_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("CODEX_PROXY_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],
  CODEX_PROXY_AUTO_HEAP_SNAPSHOT: truthy("CODEX_PROXY_AUTO_HEAP_SNAPSHOT"),
  CODEX_PROXY_GIT_BASH_PATH: process.env["CODEX_PROXY_GIT_BASH_PATH"],
  CODEX_PROXY_CONFIG: process.env["CODEX_PROXY_CONFIG"],
  CODEX_PROXY_CONFIG_CONTENT: process.env["CODEX_PROXY_CONFIG_CONTENT"],
  CODEX_PROXY_DISABLE_AUTOUPDATE: truthy("CODEX_PROXY_DISABLE_AUTOUPDATE"),
  CODEX_PROXY_ALWAYS_NOTIFY_UPDATE: truthy("CODEX_PROXY_ALWAYS_NOTIFY_UPDATE"),
  CODEX_PROXY_DISABLE_PRUNE: truthy("CODEX_PROXY_DISABLE_PRUNE"),
  CODEX_PROXY_DISABLE_TERMINAL_TITLE: truthy("CODEX_PROXY_DISABLE_TERMINAL_TITLE"),
  CODEX_PROXY_SHOW_TTFD: truthy("CODEX_PROXY_SHOW_TTFD"),
  CODEX_PROXY_DISABLE_AUTOCOMPACT: truthy("CODEX_PROXY_DISABLE_AUTOCOMPACT"),
  CODEX_PROXY_DISABLE_MODELS_FETCH: truthy("CODEX_PROXY_DISABLE_MODELS_FETCH"),
  CODEX_PROXY_DISABLE_MOUSE: truthy("CODEX_PROXY_DISABLE_MOUSE"),
  CODEX_PROXY_FAKE_VCS: process.env["CODEX_PROXY_FAKE_VCS"],
  CODEX_PROXY_SERVER_PASSWORD: process.env["CODEX_PROXY_SERVER_PASSWORD"],
  CODEX_PROXY_SERVER_USERNAME: process.env["CODEX_PROXY_SERVER_USERNAME"],
  CODEX_PROXY_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("CODEX_PROXY_DISABLE_FFF"),
  CODEX_PROXY_EXPERIMENTAL_FILEWATCHER: Config.boolean("CODEX_PROXY_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEX_PROXY_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CODEX_PROXY_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEX_PROXY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CODEX_PROXY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CODEX_PROXY_MODELS_URL: process.env["CODEX_PROXY_MODELS_URL"],
  CODEX_PROXY_MODELS_PATH: process.env["CODEX_PROXY_MODELS_PATH"],
  CODEX_PROXY_DB: process.env["CODEX_PROXY_DB"],
  CODEX_PROXY_WORKSPACE_ID: process.env["CODEX_PROXY_WORKSPACE_ID"],
  CODEX_PROXY_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CODEX_PROXY_EXPERIMENTAL_WORKSPACES"),
  get CODEX_PROXY_DISABLE_PROJECT_CONFIG() {
    return truthy("CODEX_PROXY_DISABLE_PROJECT_CONFIG")
  },
  get CODEX_PROXY_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("CODEX_PROXY_EXPERIMENTAL_REFERENCES")
  },
  get CODEX_PROXY_TUI_CONFIG() {
    return process.env["CODEX_PROXY_TUI_CONFIG"]
  },
  get CODEX_PROXY_CONFIG_DIR() {
    return process.env["CODEX_PROXY_CONFIG_DIR"]
  },
  get CODEX_PROXY_PURE() {
    return truthy("CODEX_PROXY_PURE")
  },
  get CODEX_PROXY_PERMISSION() {
    return process.env["CODEX_PROXY_PERMISSION"]
  },
  get CODEX_PROXY_PLUGIN_META_FILE() {
    return process.env["CODEX_PROXY_PLUGIN_META_FILE"]
  },
  get CODEX_PROXY_CLIENT() {
    return process.env["CODEX_PROXY_CLIENT"] ?? "cli"
  },
}
